CREATE TABLE TBL_USER(
	userid		VARCHAR2(100),
	userpw		VARCHAR2(200),
	username	VARCHAR2(100),
	userage		NUMBER(3),
	userphone	VARCHAR2(11),
	useraddr	VARCHAR2(300),
	likeCnt		NUMBER(5),
	tradeCnt	NUMBER(5),
	CONSTRAINT USER_PK PRIMARY KEY(USERID)
);

CREATE TABLE TBL_PRODUCT(
	prodnum		NUMBER(10),
	prodname	VARCHAR2(200),
	prodprice	NUMBER(12),
	prodamount	NUMBER(5),
	prodinfo	VARCHAR2(1000),
	likeCnt		NUMBER(5),
	userid		VARCHAR2(100),
	CONSTRAINT PRODUCT_PK PRIMARY KEY(USERID),
	CONSTRAINT PRODUCT_USER_FK FOREIGN KEY(USERID) REFERENCES TBL_USER(USERID)
);

SELECT * FROM TBL_USER WHERE USERID='apple';
SELECT * FROM TBL_PRODUCT WHERE PRODNAME='Áö¿ì°³';